[theme]
primaryColor = "#00f2ff"      # Тот самый неоновый голубой
backgroundColor = "#050508"   # Глубокий черный космос
secondaryBackgroundColor = "#101015"
textColor = "#ffffff"
font = "sans serif"